'use strict';

module.exports = [
		{
			title: 'Blog Post 1',
			date: 'July 5, 2017',
			content: '<p>Lorem ipsum dolor sit amet, molestie eget wisi aliquet dolor, laoreet velit elit mauris maecenas ut, dignissim feugiat at velit. Magna vivamus scelerisque volutpat. Torquent nulla tempus, hic ligula nulla rhoncus vulputate wisi eos. Purus vestibulum. Nascetur maecenas aliquet condimentum molestie integer diam, nulla ad, euismod vulputate felis neque metus, donec habitasse donec sem tortor donec esse, tellus neque vel lacinia gravida. Cursus pellentesque proin in, lectus urna tortor posuere posuere, posuere est egestas varius erat porttitor ipsum, felis at semper eu. Mi purus ligula sapien, amet phasellus mauris erat quia tortor. Senectus sit eget a fringilla, eleifend ipsum suscipit ac pede, tincidunt inceptos. Non amet morbi. Libero ante, dapibus maecenas, sed diamlorem, sed venenatis volutpat aptent egestas fermentum non, lorem eu urna at ultrices metus vestibulum.</p><p>Ante vestibulum suscipit dui lacus, maecenas nunc odio etiam mi nec, fermentum faucibus feugiat non sit arcu nonummy, metus nullam suscipit felis scelerisque qui maecenas, consequat eu purus. Vestibulum velit lacus mattis ut, litora leo amet maecenas vestibulum. Euismod luctus wisi enim eveniet magna nec, iaculis leo odio sit in, mi a. Sit morbi tristique turpis, vulputate ut eget suspendisse sapien in aliquet. Amet sit urna bibendum vitae, erat mauris urna odio. Pede gravida potenti odio erat libero.</p><p>Scelerisque molestie cras duis neque neque viverra, tellus turpis nam vestibulum ipsum ultricies ac. Quis urna phasellus condimentum dolores, felis pellentesque dignissim, et eu consequat, lacus risus ullamcorper integer. Velit erat dolor pharetra. Lectus in sed nec, elementum nulla vestibulum id dolor sit, tellus in quis nobis maecenas etiam, ac a libero libero vitae nibh sed, vivamus fringilla nullam. Massa urna nonummy vitae, aliquam odio sapien deserunt elit sem, phasellus ligula ipsum amet, rutrum ipsum platea quis mauris. Vestibulum urna leo eleifend.</p>'
		},
		{
			title: 'Blog Post 2',
			date: 'July 6, 2017',
			content: '<p>Lorem ipsum dolor sit amet, mauris gravida fames quisque, elementum sodales aliquet sit nunc unde, etiam dictum consectetuer lorem, mollis lobortis sed blandit. Sed suscipit augue. Eros consequat et metus, pellentesque dignissim nullam convallis quis mauris sit. Ac ad semper. Risus habitasse, magna non pellentesque a ac ullamcorper, egestas luctus consequat, suspendisse id adipiscing bibendum. Praesent at integer, vel maecenas, integer in massa cum, vestibulum volutpat elementum sollicitudin tempor, rutrum vel adipiscing in ante nunc mauris. Ut veniam pellentesque gravida, lectus conubia est pede tortor tellus, morbi arcu commodo molestie fusce phasellus praesent. Elit nulla in, et donec, velit eu, aliquam vitae tortor. Cras urna suspendisse dicta, porta faucibus potenti morbi rutrum, iaculis dui eu, sodales unde at molestie at. Vestibulum libero donec integer eget ipsum.</p><p>Tortor sed eleifend facilisi irure metus faucibus, tellus velit. Minima amet morbi, cursus libero blandit ante elementum, elementum fringilla nostra. Elit pretium tincidunt eu et dolor, eu velit nullam arcu ac, sociis nec malesuada lorem auctor, neque aliquam est et egestas ultricies a. Magna tincidunt nonummy accumsan neque, massa commodo commodo, vel mus, sed donec sit nulla. Praesent libero, pulvinar sed ante integer nec class hendrerit, lorem curabitur, at luctus neque duis ut molestie et, in wisi eget ligula suscipit bibendum id. Mi viverra wisi elementum, convallis convallis, vestibulum odio, amet urna dis, nullam urna odio elit tincidunt est nec. Sed suspendisse morbi nunc ac suspendisse, vivamus posuere pede.</p><p>Velit mauris dictum ac, erat ac in, ultrices sed sed, class commodo diam, rutrum eu vivamus donec wisi. Ut fusce pede posuere aut congue dictum, tincidunt scelerisque sit habitant, enim ac et accumsan, sed nec turpis non libero massa, tellus est justo erat vitae. Ipsum curabitur. Erat vulputate eu, porttitor mauris dui, donec vehicula morbi sit morbi. Justo vestibulum diam consectetuer eu dolor lacinia. Nunc sodales fusce orci etiam, aliquam metus dis turpis eget, eget pellentesque minima urna vel, lacinia ac curabitur quis imperdiet nam, justo tempor condimentum quis. Nec pretium aliquam nam porttitor, aliquam ac, augue tellus libero sed et magnis, aenean sed.</p>'
		},
		{
			title: 'Blog Post 3',
			date: 'July 7, 2017',
			content: '<p>Lorem ipsum dolor sit amet, quis curabitur at lectus. Sed elit elit lobortis et, nulla a sed vel nullam, eu vulputate, dui nec tortor, nulla dapibus fringilla scelerisque nulla. Mauris ipsum pede nulla, tristique nam etiam tempus eget, risus justo sed orci eu. Nec volutpat mauris aliquam lacus sit wisi, vel cras delectus ullamcorper leo dapibus velit, vel lacus dui egestas nec pellentesque diam, dapibus ut. Donec leo tempor justo nec. Cursus adipiscing id fringilla magnis gravida, dictum vitae elit cras sollicitudin at nascetur, malesuada lobortis aliquam lorem ornare, cum nibh massa quis.</p><p>Suscipit sodales in sed facilisis. Tristique pede maecenas neque sed auctor vel. Eget felis eu, nec minim sit ligula potenti sed, facilisis pellentesque mauris mauris, sed vestibulum elit a aenean, et faucibus sed. Pede malesuada, neque quis a arcu imperdiet ut ullamcorper, ante faucibus lectus morbi, commodo sollicitudin interdum non ipsum suspendisse eleifend, adipiscing libero eu erat sapien. Nec pede vel metus molestie, massa pharetra eu lacinia dui, ipsum amet eleifend, vel torquent et, et erat lobortis rutrum nunc. Donec nunc nec quis inceptos ut, in vestibulum luctus, quis in elementum mauris, wisi amet ut sed faucibus. Dui habitasse ante mauris amet dui justo, pede ridiculus turpis magna, faucibus conubia dolor diam, dolor id consectetuer luctus sollicitudin ullamcorper.</p><p>Vel esse vivamus pede. Aliquam a, pellentesque fermentum congue leo, taciti accumsan pede, mollis in. Neque lacus bibendum cursus nulla pellentesque velit, praesent sit mauris sem tempor sodales tincidunt, cras cras massa lorem sapien. Elit ultricies rutrum molestie per iaculis sodales, dolor et fermentum, in tempor quis nulla, placerat leo nibh, aliquam potenti a lorem ipsum. Sagittis blandit eget, eros dolor enim rhoncus pede quis. Ut suscipit vel non ut, sit est tincidunt. Excepteur iaculis pede massa, massa velit duis phasellus platea.</p>'
		}
	];